- Changed: Renamed fplSetWindowFullscreen to fplSetWindowFullscreenSize  - Changed: Replaced windowWidth and windowHeight from fplWindowSettings with windowSize structure  - Changed: Replaced fullscreenWidth and fullscreenHeight from fplWindowSettings with fullscreenSize structure  - Changed: Renamed macro FPL_PLATFORM_WIN32 to FPL_PLATFORM_WINDOWS  - Changed: Renamed fplGetWindowArea() to fplGetWindowSize()  - Changed: Renamed fplSetWindowArea() to fplSetWindowSize()  - Changed: Renamed fplWindowSettings.windowTitle to fplWindowSettings.title  - Changed: Reversed buffer/max-size argument of fplS32ToString()  - Changed: Renamed fullPath into name in the fplFileEntry structure and limit its size to FPL_MAX_FILENAME_LENGTH  - Fixed: fplPlatformInit() was using the width for the height for the default window size  - Fixed: fplExtractFileExtension() was not favour the last path part  - Fixed [Win32/MSVC]: Workaround for "combaseapi.h(229): error C2187: syntax error: 'identifier' was unexpected here"  - New: Added fplSetWindowFullscreenRect()  - New: Added fplGetDisplayCount()  - New: Added fplGetDisplays()  - New: Added fplGetWindowDisplay()  - New: Added fplGetPrimaryDisplay()  - New: Added fplGetDisplayFromPosition()  - New: Added fplGetDisplayModeCount()  - New: Added fplGetDisplayModes()  - New: Added fplGetWindowTitle()
 - Changed: [Win32] fplSetWindowFullscreenSize does not use virtual screen coordinates anymore
 - Changed: [Win32/POSIX] Store filename in fplFileEntry instead of the full path
 - Fixed: [Win32] fplGetExecutableFilePath was not returning the last written character
 - Fixed: [Win32] fplGetHomePath was not returning the last written character
 - New: [Win32/X11] Use fplWindowSettings.fullscreenRefreshRate for startup when needed
 - New: [Win32] Implemented fplSetWindowFullscreenRect()
 - New: [Win32] Implemented fplGetDisplayCount()
 - New: [Win32] Implemented fplGetDisplays()
 - New: [Win32] Implemented fplGetWindowDisplay()
 - New: [Win32] Implemented fplGetPrimaryDisplay()
 - New: [Win32] Implemented fplGetDisplayFromPosition()
 - New: [Win32] Implemented fplGetDisplayModeCount()
 - New: [Win32] Implemented fplGetDisplayModes()